[package]
authors = ["Tye singwa"]
edition = "2021"
name = "lux-ai-api"
version = "3.1.0"

[lib]
path = "./src/lib.rs"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
lazy_static = "1.0"
thiserror = "1.0"
